FROM python:3.11

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY ./app/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy rest of the app
COPY ./app /app

# Set environment
ENV PYTHONPATH=/app

# Expose port
EXPOSE 8000

# Run the app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
