version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:code/app 
    working_dir: /code
    environment:
      - PYTHONPATH=/code
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]