name: Python CI Pipeline

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd CommonAssessmentTool
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt
          pip install black flake8 mypy pytest

      - name: Run Tests
        run: |
          cd CommonAssessmentTool
          python -m pytest tests/

      - name: Run Black (code formatter)
        run: |
          cd CommonAssessmentTool
          black app --check

      - name: Run Flake8 (linter)
        run: |
          cd CommonAssessmentTool
          flake8 app

      - name: Run MyPy (type checker)
        run: |
          cd CommonAssessmentTool
          mypy app

      - name: Print Success Message
        run: |
          echo "CI Pipeline completed successfully!"
          echo "========================"
          echo "✓ Code checked out"
          echo "✓ Python environment set up"
          echo "✓ Dependencies installed"
          echo "✓ Tests executed"
          echo "✓ Black check passed"
          echo "✓ Flake8 linting passed"
          echo "✓ MyPy type check passed"
          echo "========================"

